Repository public-apis/public-apis, pull requests merged in 2021-10, with the labels that each got.

#2079 Add telegraph api
  README.md
Labels: hacktoberfest-accepted

#2080 Add When is next MCU film
  README.md
Labels: hacktoberfest-accepted

#2081 Add Cowin
  README.md
Labels: hacktoberfest-accepted

#2083 Add Bruzu API in Photography
  README.md
Labels: hacktoberfest-accepted

#2087 Add Kakao API to Social
  README.md
Labels: hacktoberfest-accepted

#2088 Add NAVER API
  README.md
Labels: hacktoberfest-accepted

#2084 Add Spanish random names API
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted, update link

#2090 add songlink / odesli API
  README.md
Labels: hacktoberfest-accepted

#2092 Add Dev.to
  README.md
Labels: hacktoberfest-accepted

#2093 Add ApiMedic
  README.md
Labels: hacktoberfest-accepted

#2094 Add The Covid Tracking Project API
  README.md
Labels: hacktoberfest-accepted

#2095 Add ipfind.io
  README.md
Labels: hacktoberfest-accepted

#2096 Add CurrencyFreaks
  README.md
Labels: hacktoberfest-accepted

#2097 Add Black History Facts API
  README.md
Labels: hacktoberfest-accepted

#2099 Added Longdo Map API
  README.md
Labels: hacktoberfest-accepted

#2121 CoinRanking Auth
  README.md
Labels: hacktoberfest-accepted

#2033 Add supportivekoala API
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted

#2120 chore: added rwanda location apis
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted, alphabetical ordering is required

#2089 Add skyscanner api
  README.md
Labels: hacktoberfest-accepted

#2085 Add IMDbOT API
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted

#2101 Add Webdam
  README.md
Labels: hacktoberfest-accepted

#2111 Add Interpol Red Notices API
  README.md
Labels: hacktoberfest-accepted

#2112 Add OneSignal api
  README.md
Labels: hacktoberfest-accepted

#2076 Add APIGratis.com.br
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted

#2253 Add Nownodes API to Blockchain
  README.md
Labels: hacktoberfest-accepted

#2160 Add Utelly API
  README.md
Labels: hacktoberfest-accepted

#2129 Add WolframAlpha API to Machine Learning
  README.md
Labels: hacktoberfest-accepted

#2100 Add ipgeolocation
  README.md
Labels: hacktoberfest-accepted

#2211 Add CollegeScoreCard Data to Open Data
  README.md
Labels: hacktoberfest-accepted

#2126 Add US Weather API
  README.md
Labels: hacktoberfest-accepted

#2124 add Dangerous Discord API
  README.md
Labels: hacktoberfest-accepted

#2157 Add Logs.to API
  README.md
Labels: hacktoberfest-accepted

#2209 add Duna API
  README.md
Labels: hacktoberfest-accepted

#2128 add TLE API
  README.md
Labels: hacktoberfest-accepted

#2221 Add SAWO Labs
  README.md
Labels: hacktoberfest-accepted

#2106 Add BinaryEdge API
  README.md
Labels: hacktoberfest-accepted

#2174 Add Harry Potter Characters API
  README.md
Labels: hacktoberfest-accepted

#2176 Fix bible
  README.md
Labels: awaiting PR evolution

#2109 Add IBGE API to Geocoding
  README.md
Labels: hacktoberfest-accepted

#2114 Add Lazada
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted, update link

#2127 Add Blogger API
  README.md
Labels: hacktoberfest-accepted

#2136 Add quizapi.io
  README.md
Labels: hacktoberfest-accepted

#2143 Add Alpaca
  README.md
Labels: hacktoberfest-accepted

#2144 Add FRED <Federal Reserve Economic Data>
  README.md
Labels: hacktoberfest-accepted

#2134 Add Breezometer API
  README.md
Labels: hacktoberfest-accepted

#2146 Add The dog API
  README.md
Labels: hacktoberfest-accepted

#2149 add Line to Social
  README.md
Labels: hacktoberfest-accepted

#2150 Add Kroger API
  README.md
Labels: hacktoberfest-accepted

#2162 Add Infermedica API
  README.md
Labels: hacktoberfest-accepted

#2182 Add Tebex API
  README.md
Labels: hacktoberfest-accepted

#2772 Add Email section with Mailchimp, Sendgrid and Sendinblue
  README.md
Labels: hacktoberfest-accepted

#2781 Add Covid 19 India to Health
  README.md
Labels: hacktoberfest-accepted

#2782 Updated RijksMuseum Doc Link
  README.md
Labels: hacktoberfest-accepted

#2785 Add Open Government, Luxembourg
  README.md
Labels: hacktoberfest-accepted

#2786 Add iLovePDF to Documents & Productivity
  README.md
Labels: hacktoberfest-accepted

#2787 Add Land Transport Authority DataMall, Singapore
  README.md
Labels: hacktoberfest-accepted

#2788 Add Heroku Platform API
  README.md
Labels: hacktoberfest-accepted

#2794 Add genshin.dev
  README.md
Labels: hacktoberfest-accepted

#2795 Add Open Data Minneapolis API
  README.md
Labels: hacktoberfest-accepted

#2797 Add Universalis (FFXIV)
  README.md
Labels: hacktoberfest-accepted

#2798 Add Mattermost
  README.md
Labels: hacktoberfest-accepted

#2799 Add Monster Hunter World
  README.md
Labels: hacktoberfest-accepted

#2800 Add Indian Mutual Fund
  README.md
Labels: hacktoberfest-accepted

#2802 Add Gateio to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2808 Add Kickbox
  README.md
Labels: hacktoberfest-accepted

#2766 Add TETR.IO Tetra Channel API
  README.md
Labels: hacktoberfest-accepted

#2805 Add Localbitcoins API
  README.md
Labels: hacktoberfest-accepted

#2806 Add Mempool to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2810 Update Random Stuff
  README.md
Labels: hacktoberfest-accepted

#2813 Add NBA Data to Sports and Fitness
  README.md
Labels: hacktoberfest-accepted

#2814 Add Tasty API to Food and Drink
  README.md
Labels: hacktoberfest-accepted

#2816 Add Squiggle API to Sports & Fitness
  README.md
Labels: hacktoberfest-accepted

#2817 Added Trove API to News
  README.md
Labels: hacktoberfest-accepted

#2822 Updated SwiftKanban Link
  README.md
Labels: hacktoberfest-accepted

#2791 Added "Catch The Show"
  README.md
Labels: hacktoberfest-accepted

#2823 Add GurbaniNow
  README.md
Labels: hacktoberfest-accepted

#2824 Add OpenGraphr to Development
  README.md
Labels: hacktoberfest-accepted

#2827 Add SEC EDGAR data API to finance
  README.md
Labels: hacktoberfest-accepted

#2811 Update Icons8 API
  README.md
Labels: hacktoberfest-accepted

#2831 Add Blague API
  README.md
Labels: hacktoberfest-accepted

#2829 Add LordIcon Library
  README.md
Labels: hacktoberfest-accepted

#2741 OLX Poland
  README.md
Labels: hacktoberfest-accepted

#2832 Add CTS API
  README.md
Labels: hacktoberfest-accepted

#2837 Add Superset API to Business
  README.md
Labels: hacktoberfest-accepted

#2838 Add Redash API to Business
  README.md
Labels: hacktoberfest-accepted
