Repository public-apis/public-apis, pull requests merged in 2021-11, with the labels that each got.

#2841 Add KuCoin API to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2842 Add OKEx API to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2843 Add dYdX API to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2844 Add Huobi API to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2845 Add EXMO API to Cryptocurrency
  README.md
Labels: hacktoberfest-accepted

#2847 Add ZenRows API to Development
  README.md
Labels: hacktoberfest-accepted

#2851 Add MyVaccination (Malaysia)
  README.md
Labels: hacktoberfest-accepted

#2852 Add Gaana API
  README.md
Labels: hacktoberfest-accepted

#2853 Add Goodreads API to the list
  README.md
Labels: hacktoberfest-accepted

#2855 Add City, Kyiv
  README.md
Labels: hacktoberfest-accepted

#2856 Add City, Lviv
  README.md
Labels: hacktoberfest-accepted

#2860 Add GeneradorDNI
  README.md
Labels: hacktoberfest-accepted

#2865 Add Amdoren API to Currency Exchange
  README.md
Labels: hacktoberfest-accepted

#2868 Add Boleto.Cloud API
  README.md
Labels: hacktoberfest-accepted

#2870 Add pinball map API
  README.md
Labels: hacktoberfest-accepted

#2850 Add BIC-Boxtech
  README.md
Labels: hacktoberfest-accepted

#2854 Add Open Government in Ukraine to the list
  README.md
Labels: hacktoberfest-accepted

#2863 Add Poetry DB under Books
  README.md
Labels: hacktoberfest-accepted

#2912 Add APITemplate.io
  README.md
Labels: awaiting PR evolution

#2746 Adding OpenLigaDB
  README.md
Labels: awaiting PR evolution, hacktoberfest-accepted

#2914 Add GetOTP API
  README.md
Labels: awaiting PR evolution

#2875 Add Billplz
  README.md
Labels: awaiting PR evolution

#2910 Add Mailjet API to Business
  README.md
Labels: awaiting PR evolution

#2926 Add Classify API to Security
  README.md
Labels: awaiting PR evolution
