Repository public-apis/public-apis, pull requests merged in 2021-05, with the labels that each got.

#1441 added IPS video and image anonymization api
  README.md
Labels: Resolve conflict required

#1471 Add Cartes.io mapping API
  README.md
Labels: Resolve conflict required

#1635 Added API of Audiomack
  README.md
Labels: question

#1634 Added Apple Music API
  README.md
Labels: Resolve conflict required

#1572 Add QuickMocker API to the Test Data section
  README.md
Labels: squash required

#1636 Added API of Bandcamp
  README.md
Labels: question

#1651 add financial api info
  README.md
Labels: Resolve conflict required

#1640 Add Glitterly
  README.md
Labels: Awaiting PR evolution

#1713 Added CCDB and CText
  README.md
Labels: Awaiting PR evolution

#1717 Fixer HTTPs is a paid feature
  README.md
Labels: Awaiting PR evolution

#1712 Add URLHaus API
  README.md
Labels: Awaiting PR evolution

#1743 Add Notion api
  README.md
Labels: Awaiting PR evolution, squash required

#1677 Add WallstreetBets
  README.md
Labels: Awaiting PR evolution
