Repository public-apis/public-apis, pull requests merged in 2021-04, with the labels that each got.

#1284 Add UK government API catalogue
  README.md
Labels: Resolve conflict required

#1261 Add a RESTful free API to check the weather
  README.md
Labels: Resolve conflict required

#1294 Added hubblesite API
  README.md
Labels: Awaiting PR evolution, Resolve conflict required

#1133 Added Technical Analysis API
  README.md
Labels: Awaiting PR evolution

#1273 Add mozilla observatory
  README.md
Labels: Resolve conflict required, Update Link

#1568 Add Shikimory
  README.md
Labels: Resolve conflict required

#1531 Add NLP Cloud API
  README.md
Labels: Resolve conflict required, squash required

#1444 Added troposphere.io weather API
  README.md
Labels: Awaiting PR evolution, Resolve conflict required

#1361 Added Unixtime conversion service
  README.md
Labels: Awaiting PR evolution, Resolve conflict required

#1667 Make CONTRIBUTING.md more precise and clear.
  CONTRIBUTING.md
Labels: enhancement

#1343 Added EVA under Data Validation category
  README.md
Labels: Awaiting PR evolution, Resolve conflict required

#1617 Add Visual Crossing Weather API
  README.md
Labels: Resolve conflict required
